---
title: CONACYT - Arquitectura
timezone: America/Mexico
collections:
  git:
    title: Git
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Lineamientos para Desarrolladores
      badge: "/uploads/logos/git-icon.svg"
      in_nav: true
    position: 60
  api:
    title: API
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Lineamientos para APIs
      badge: "/uploads/badge--api.svg"
      in_nav: true
    position: 60
  posts:
    title: Posts
    output: true
  style:
    title: Guía de Estilos
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: A guide to Siteleaf style
      in_nav: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: getting-started
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: content
  values:
    layout: page
    color: green
- scope:
    path: ''
    type: themes
  values:
    layout: page
    color: yellow
- scope:
    path: ''
    type: sites
  values:
    layout: page
    color: red
- scope:
    path: ''
    type: api
  values:
    layout: page
    color: purple
- scope:
    path: ''
    type: git
  values:
    layout: page
    color: purple
- scope:
    path: ''
    type: v1
  values:
    layout: page
- scope:
    path: ''
    type: style
  values:
    layout: page
    color: darkest-gray
- scope:
    path: ''
    type: posts
  values:
    layout: page
    color: red
url: https://conacyt-arquitectura.github.io/
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- ".gitignore"
github_url: https://github.com/conacyt-arquitectura
sass:
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
logo: "/assets/images/logo.png"
description: Documentation and learning resource for Siteleaf, a content management
  system designed for a better web.
